### ISSUE TITLE
Error thrown when using room ID as a number

### ISSUE THREAD

**Issue by iascan** [jmccann/drone-hipchat#11]
The following config resulted in the error:

```
notify:
  hipchat:
    auth_token: {my_token}
    room_id_or_name: 1466987
    from: drone
    notify: true
```

`panic: Unable to unarmshal vargs. json: cannot unmarshal number into Go value of type string\n\ngoroutine 1 [running]:\ngithub.com/drone/drone-go/plugin.MustParse()\n\t/drone/src/github.com/drone/drone-go/plugin/plugin.go:132 +0x59\nmain.main()\n\t/drone/src/github.com/drone-plugins/drone-hipchat/main.go:28 +0x55a\n[info] build failed (exit code 2)\n`

Using this config worked:

```
notify:
  hipchat:
    auth_token: '{my_token}'
    room_id_or_name: '1466987'
    from: 'drone'
    notify: true
```
