### ISSUE TITLE
Private Server

### ISSUE THREAD

**Issue by davidak** [jmccann/drone-hipchat#15]
We have a private, self hosted Hipchat-Server.

Please add a Parameter to set the base URL like

```
notify:
  hipchat:
    host: hipchat.company.com
    secured: true #default (SSL)
    auth_token: xxxxxxxxxx
    room_id_or_name: 42
    notify: false
```

the call is then: `https://hipchat.company.com/v2/room/42/...`
